import{a as M,S as P,i as a}from"./assets/vendor-DcHCnVjq.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="56017370-7aa7005f41ba7433eba06fcfc",B="https://pixabay.com/api/";async function u(r,e){const s={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await M.get(B,{params:s})).data}const $=new P(".gallery a",{captionsData:"alt",captionDelay:250}),f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more-btn");function y(r){const e=r.map(({webformatURL:s,largeImageURL:n,tags:t,likes:o,views:i,comments:v,downloads:w})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${s}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><br>${o}</p>
          <p class="info-item"><b>Views</b><br>${i}</p>
          <p class="info-item"><b>Comments</b><br>${v}</p>
          <p class="info-item"><b>Downloads</b><br>${w}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",e),$.refresh()}function O(){f.innerHTML=""}function g(){m.classList.remove("is-hidden")}function p(){m.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden")}function d(){h.classList.add("is-hidden")}const L=document.querySelector(".search-form"),x=document.querySelector(".load-more-btn");let l="",c=1;const S=15;L.addEventListener("submit",E);x.addEventListener("click",H);async function E(r){if(r.preventDefault(),l=r.currentTarget.elements.userQuery.value.trim(),!l){a.warning({message:"Будь ласка, введіть слово для пошуку!"});return}c=1,O(),d(),g();try{const e=await u(l,c);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(e.hits),Math.ceil(e.totalHits/S)>1?b():a.info({message:"We're sorry, but you've reached the end of search results."})}catch(e){a.error({message:"Сталася помилка при завантаженні даних."}),console.error(e)}finally{p(),L.reset()}}async function H(){c+=1,d(),g();try{const r=await u(l,c);y(r.hits);const e=Math.ceil(r.totalHits/S);c>=e?(d(),a.info({message:"We're sorry, but you've reached the end of search results."})):b(),A()}catch(r){a.error({message:"Не вдалося завантажити додаткові зображення."}),console.error(r)}finally{p()}}function A(){const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
